#!/usr/bin/env python3
"""nt-bootstrap.py — Dedicated NetworkTracing bootstrap & bundle distribution server on port 30105.

Separated service:
- Serves POSIX bootstrap script on GET /bootstrap or /bootstrap.sh
- Serves complete deployment archive on GET /bundle.tar.gz
- Serves installer on GET /install.sh
- Serves health check on GET /healthz
- Agent simulator: background threads post realistic AGENT-STATS-PROTOCOL v1 samples to the hub
  every SIMULATE_INTERVAL seconds (default 30) for SIMULATE_AGENTS simulated nodes (default 3).
  Set SIMULATE_AGENTS=0 to disable. Set HUB_HOST / HUB_PORT to target a different hub.
- Default port: 30105 (configurable via BOOTSTRAP_PORT)
- Hub telemetry port: 30102 (configurable via HUB_PORT)
"""

import math
import hashlib
import os
import random
import socket
import sys
import json
import time
import tarfile
import threading
import urllib.request
import urllib.error
import re
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PARENT_DIR = os.path.dirname(BASE_DIR)
BUNDLE_SRC_DIR = os.environ.get("BUNDLE_SRC_DIR", os.path.join(PARENT_DIR, "bundle"))
BUNDLE_TAR_PATH = os.environ.get("BUNDLE_TAR_PATH", os.path.join(BASE_DIR, "bundle.tar.gz"))

BOOTSTRAP_PORT = int(os.environ.get("BOOTSTRAP_PORT", "30105"))
HUB_PORT = int(os.environ.get("HUB_PORT", "30102"))
DEFAULT_HOST = os.environ.get("HUB_HOST", "")
PUBLIC_URL = os.environ.get("BOOTSTRAP_PUBLIC_URL", "").rstrip("/")

tar_lock = threading.Lock()


def _bundle_outdated():
    """True if any file under BUNDLE_SRC_DIR is newer than BUNDLE_TAR_PATH."""
    if not os.path.exists(BUNDLE_TAR_PATH):
        return True
    try:
        tar_mtime = os.path.getmtime(BUNDLE_TAR_PATH)
    except OSError:
        return True
    for root, _dirs, files in os.walk(BUNDLE_SRC_DIR):
        for name in files:
            p = os.path.join(root, name)
            try:
                if os.path.getmtime(p) > tar_mtime:
                    return True
            except OSError:
                continue
    return False


def ensure_bundle_tar():
    """Ensure bundle.tar.gz exists by packaging BUNDLE_SRC_DIR if missing or outdated."""
    with tar_lock:
        if os.path.exists(BUNDLE_TAR_PATH) and os.path.getsize(BUNDLE_TAR_PATH) > 0 \
                and not _bundle_outdated():
            return BUNDLE_TAR_PATH
        if not os.path.isdir(BUNDLE_SRC_DIR):
            return None
        print(f"[nt-bootstrap] Packaging bundle from {BUNDLE_SRC_DIR} -> {BUNDLE_TAR_PATH}...", flush=True)
        tmp_tar = BUNDLE_TAR_PATH + ".tmp"
        try:
            with tarfile.open(tmp_tar, "w:gz") as tar:
                # Exclude local caches from the deployment archive.
                for item in os.listdir(BUNDLE_SRC_DIR):
                    if item in ("__pycache__", ".git"):
                        continue
                    item_path = os.path.join(BUNDLE_SRC_DIR, item)
                    tar.add(item_path, arcname=item)
            os.replace(tmp_tar, BUNDLE_TAR_PATH)
            print(f"[nt-bootstrap] Created {BUNDLE_TAR_PATH} ({os.path.getsize(BUNDLE_TAR_PATH)} bytes)", flush=True)
            return BUNDLE_TAR_PATH
        except Exception as e:
            print(f"[nt-bootstrap] Error packaging bundle: {e}", file=sys.stderr, flush=True)
            if os.path.exists(tmp_tar):
                try:
                    os.remove(tmp_tar)
                except OSError:
                    pass
            return None


def _sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def generate_bootstrap_script(hub_host, bootstrap_port, hub_port, bootstrap_url=None, bundle_sha256=None):
    """Generate a 100% POSIX /bin/sh script to bootstrap the agent on remote nodes."""
    return f"""#!/bin/sh
# NetworkTracing remote agent bootstrap script (POSIX sh)
# Auto-generated by bootstrap server at port {bootstrap_port}
set -eu

BOOTSTRAP_HOST="{hub_host}"
BOOTSTRAP_PORT="{bootstrap_port}"
HUB_HOST="{hub_host}"
HUB_PORT="{hub_port}"

BOOTSTRAP_URL="{bootstrap_url or f'https://{hub_host}:{bootstrap_port}'}"
EXPECTED_SHA256="{bundle_sha256 or ''}"
HUB_ENDPOINT="http://${{HUB_HOST}}:${{HUB_PORT}}"

# Parse any custom arguments passed to bootstrap
EXTRA_ARGS=""
while [ $# -gt 0 ]; do
    case "$1" in
        --endpoint)
            HUB_ENDPOINT="${{2:?--endpoint requires a URL}}"
            shift 2
            ;;
        *)
            EXTRA_ARGS="$EXTRA_ARGS $1"
            shift
            ;;
    esac
done

log()  {{ echo "[nt-bootstrap] $*"; }}
warn() {{ echo "[nt-bootstrap] WARN: $*" >&2; }}
die()  {{ echo "[nt-bootstrap] FAIL: $*" >&2; exit 1; }}

[ "$(id -u)" = 0 ] || die "bootstrap must be run as root (or with sudo)"

TMPDIR=$(mktemp -d /tmp/nt-bootstrap.XXXXXX)
cleanup() {{
    rm -rf "$TMPDIR"
}}
trap cleanup EXIT INT TERM

log "NetworkTracing Agent Bootstrap"
log "Bootstrap source : $BOOTSTRAP_URL"
log "Target Hub endpoint: $HUB_ENDPOINT"
log "Temporary working dir: $TMPDIR"

# Download helper (curl or wget)
download_file() {{
    _url="$1"
    _dest="$2"
    if command -v curl >/dev/null 2>&1; then
        curl -sSfL "$_url" -o "$_dest"
    elif command -v wget >/dev/null 2>&1; then
        wget -qO "$_dest" "$_url"
    else
        die "Neither curl nor wget found on this system. Please install curl or wget."
    fi
}}

log "Downloading deployment bundle from $BOOTSTRAP_URL/bundle.tar.gz..."
download_file "$BOOTSTRAP_URL/bundle.tar.gz" "$TMPDIR/bundle.tar.gz" || die "Failed to download bundle archive"

[ -n "$EXPECTED_SHA256" ] || die "Bootstrap bundle digest is not configured"
if command -v sha256sum >/dev/null 2>&1; then
    printf '%s  %s\n' "$EXPECTED_SHA256" "$TMPDIR/bundle.tar.gz" | sha256sum -c - >/dev/null 2>&1 || die "Bundle SHA-256 verification failed"
elif command -v openssl >/dev/null 2>&1; then
    _actual=$(openssl dgst -sha256 "$TMPDIR/bundle.tar.gz" | sed 's/^.*= //')
    [ "$_actual" = "$EXPECTED_SHA256" ] || die "Bundle SHA-256 verification failed"
else
    die "sha256sum or openssl is required to authenticate the bundle"
fi

log "Extracting bundle..."
tar -xzf "$TMPDIR/bundle.tar.gz" -C "$TMPDIR" || die "Failed to extract bundle archive"

[ -f "$TMPDIR/install.sh" ] || die "Bundle is invalid: missing install.sh"

log "Executing installer in AGENT mode..."
# Pass target endpoint and any additional arguments
# shellcheck disable=SC2086
sh "$TMPDIR/install.sh" --endpoint "$HUB_ENDPOINT" $EXTRA_ARGS

case "$EXTRA_ARGS" in
    *--uninstall*)
        log "============================================================"
        log "NetworkTracing agent has been completely uninstalled."
        log "============================================================"
        ;;
    *--check*)
        ;;
    *)
        log "============================================================"
        log "Bootstrap complete! Agent is installed and shipping to $HUB_ENDPOINT"
        log "============================================================"
        ;;
esac
"""


def generate_oldkernel_bootstrap_script(hub_host, bootstrap_port, hub_port, bootstrap_url=None, installer_sha256=None):
    """Generate a 100% POSIX /bin/sh script to bootstrap the legacy agent on CentOS 6.x / 2.6.32+ nodes."""
    return f"""#!/bin/sh
# NetworkTracing Oldkernel Agent Bootstrap Script (POSIX sh)
# Auto-generated by bootstrap server at port {bootstrap_port} for CentOS 6.x / Kernel 2.6.32+
set -eu

BOOTSTRAP_HOST="{hub_host}"
BOOTSTRAP_PORT="{bootstrap_port}"
HUB_HOST="{hub_host}"
HUB_PORT="{hub_port}"

BOOTSTRAP_URL="{(bootstrap_url or f'https://{hub_host}:{bootstrap_port}') + '/oldkernel'}"
EXPECTED_SHA256="{installer_sha256 or ''}"
HUB_ENDPOINT="http://${{HUB_HOST}}:${{HUB_PORT}}"

# Parse any custom arguments passed to bootstrap
EXTRA_ARGS=""
while [ $# -gt 0 ]; do
    case "$1" in
        --server)
            _srv="${{2:?--server requires a hostname, IP or URL}}"
            case "$_srv" in
                http://*|https://*)
                    HUB_ENDPOINT="$_srv"
                    HUB_HOST=$(printf %s "$_srv" | sed -n 's#^\(https\?://[^/:]*\).*$#\1#p' | sed 's#^https\?://##')
                    ;;
                *:*)
                    HUB_ENDPOINT="http://${{_srv}}"
                    HUB_HOST="${{_srv%%:*}}"
                    ;;
                *)
                    HUB_ENDPOINT="http://${{_srv}}:${{HUB_PORT}}"
                    HUB_HOST="$_srv"
                    ;;
            esac
            BOOTSTRAP_URL="http://${{HUB_HOST}}:${{BOOTSTRAP_PORT}}/oldkernel"
            shift 2
            ;;
        --endpoint)
            _ep="${{2:?--endpoint requires a URL}}"
            case "$_ep" in
                http://*|https://*) HUB_ENDPOINT="$_ep" ;;
                *) HUB_ENDPOINT="http://${{_ep}}" ;;
            esac
            shift 2
            ;;
        --kit-url|--hub)
            BOOTSTRAP_URL="${{2:?--kit-url requires a URL}}"
            shift 2
            ;;
        *)
            EXTRA_ARGS="$EXTRA_ARGS $1"
            shift
            ;;
    esac
done

log()  {{ echo "[nt-oldkernel-bootstrap] $*"; }}
warn() {{ echo "[nt-oldkernel-bootstrap] WARN: $*" >&2; }}
die()  {{ echo "[nt-oldkernel-bootstrap] FAIL: $*" >&2; exit 1; }}

[ "$(id -u)" = 0 ] || die "bootstrap must be run as root (or with sudo)"

TMPDIR=$(mktemp -d /tmp/nt-oldkernel-boot.XXXXXX 2>/dev/null || mktemp -d -t 'nt-oldkernel-boot')
cleanup() {{
    rm -rf "$TMPDIR"
}}
trap cleanup EXIT INT TERM

log "NetworkTracing Oldkernel Agent Bootstrap (CentOS 6.x / 2.6.32+)"
log "Bootstrap source : $BOOTSTRAP_URL"
log "Target Hub endpoint: $HUB_ENDPOINT"
log "Temporary working dir: $TMPDIR"

# Download helper (curl or wget)
download_file() {{
    _url="$1"
    _dest="$2"
    if command -v curl >/dev/null 2>&1; then
        curl -sSfL "$_url" -o "$_dest"
    elif command -v wget >/dev/null 2>&1; then
        wget -qO "$_dest" "$_url"
    else
        die "Neither curl nor wget found on this system. Please install curl or wget."
    fi
}}

log "Downloading self-contained installer from $BOOTSTRAP_URL/install-firstrun-el68.sh..."
download_file "$BOOTSTRAP_URL/install-firstrun-el68.sh" "$TMPDIR/install-firstrun-el68.sh" || die "Failed to download installer"
[ -n "$EXPECTED_SHA256" ] || die "Bootstrap installer digest is not configured"
if command -v sha256sum >/dev/null 2>&1; then
    printf '%s  %s\n' "$EXPECTED_SHA256" "$TMPDIR/install-firstrun-el68.sh" | sha256sum -c - >/dev/null 2>&1 || die "Installer SHA-256 verification failed"
else
    _actual=$(openssl dgst -sha256 "$TMPDIR/install-firstrun-el68.sh" | sed 's/^.*= //')
    [ "$_actual" = "$EXPECTED_SHA256" ] || die "Installer SHA-256 verification failed"
fi
chmod 755 "$TMPDIR/install-firstrun-el68.sh"

log "Executing installer..."
# shellcheck disable=SC2086
sh "$TMPDIR/install-firstrun-el68.sh" --server "$HUB_ENDPOINT" --kit-url "$BOOTSTRAP_URL" $EXTRA_ARGS

case "$EXTRA_ARGS" in
    *--uninstall*)
        log "============================================================"
        log "NetworkTracing legacy agent has been completely uninstalled."
        log "============================================================"
        ;;
    *--check*)
        ;;
    *)
        log "============================================================"
        log "Bootstrap complete! Oldkernel agent is running and shipping to $HUB_ENDPOINT"
        log "============================================================"
        ;;
esac
"""




class BootstrapHandler(BaseHTTPRequestHandler):
    server_version = "nt-bootstrap/1.0"

    def log_message(self, format, *args):
        print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {self.address_string()} - {format % args}", flush=True)

    def _reply_json(self, status, data):
        body = json.dumps(data, indent=2).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Connection", "close")
        self.end_headers()
        if not getattr(self, "_is_head", False):
            self.wfile.write(body)

    def _reply_text(self, status, text, content_type="text/plain; charset=utf-8"):
        body = text.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Connection", "close")
        self.end_headers()
        if not getattr(self, "_is_head", False):
            self.wfile.write(body)

    def _get_hub_host(self):
        """Determine the IP or hostname of the hub."""
        if DEFAULT_HOST:
            candidate = DEFAULT_HOST
        else:
            host_hdr = self.headers.get("Host", "")
            if host_hdr.startswith("[") and "]" in host_hdr:
                candidate = host_hdr.split("]")[0] + "]"
            else:
                candidate = host_hdr.split(":")[0]
        if candidate and re.fullmatch(r"(?:[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?|\[[0-9A-Fa-f:]+\])", candidate):
            return candidate
        return None

    def do_HEAD(self):
        self._is_head = True
        self.do_GET()

    def do_GET(self):
        raw_path = self.path
        query = ""
        if "?" in raw_path:
            path_part, query = raw_path.split("?", 1)
        else:
            path_part = raw_path
        path = path_part.rstrip("/")
        if path == "":
            path = "/"

        # Check for mode=oldkernel or legacy in query string
        is_oldkernel_query = False
        if query:
            for qp in query.split("&"):
                if qp in ("mode=oldkernel", "oldkernel=1", "legacy=1", "mode=legacy"):
                    is_oldkernel_query = True
                    break

        # Health check
        if path in ("/healthz", "/health"):
            tar_ready = os.path.exists(BUNDLE_TAR_PATH) and os.path.getsize(BUNDLE_TAR_PATH) > 0
            return self._reply_json(200, {
                "status": "ok",
                "service": "networktracing-bootstrap",
                "bootstrap_port": BOOTSTRAP_PORT,
                "hub_port": HUB_PORT,
                "bundle_ready": tar_ready,
                "bundle_src": BUNDLE_SRC_DIR,
                "timestamp": int(time.time()),
            })

        # Landing / instructions page
        if path == "/":
            hub_host = self._get_hub_host()
            help_text = f"""NetworkTracing Dedicated Bootstrap Server (: {BOOTSTRAP_PORT})
============================================================

Quick Agent Installation (run on target node):
  Modern Nodes (Kernel >= 5.5, eBPF):
    curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/bootstrap | sudo -n sh

  Legacy Nodes (CentOS 6.x / Kernel 2.6.32+):
    curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/bootstrap | sudo -n sh
    (or: curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/bootstrap?mode=oldkernel | sudo -n sh)

Check-only preflight (no modifications):
  Modern: curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/bootstrap | sudo -n sh -s -- --check
  Legacy: curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/bootstrap | sudo -n sh -s -- --check

Uninstall agent:
  Modern: curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/bootstrap | sudo -n sh -s -- --uninstall
  Legacy: curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/bootstrap | sudo -n sh -s -- --uninstall

Direct Downloads:
  Modern Bootstrap script:    http://{hub_host}:{BOOTSTRAP_PORT}/bootstrap
  Oldkernel Bootstrap script: http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/bootstrap
  Bundle archive:             http://{hub_host}:{BOOTSTRAP_PORT}/bundle.tar.gz
  Install script:             http://{hub_host}:{BOOTSTRAP_PORT}/install.sh
  Health check:               http://{hub_host}:{BOOTSTRAP_PORT}/healthz

Old-kernel Kit (CentOS 6.x / 2.6.32):
  One-line Bootstrap: http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/bootstrap
  First-run Bundle:   http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/install-firstrun-el68.sh
  C++ Sniffer:        http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/nt-sniff-cpp.cpp
  C++ Shipper:        http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/nt-ship-cpp.cpp
  Installer:          http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/install-oldkernel.sh
  Resource Guard:     http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/nt-resource-guard.sh
  Supervisor:         http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/nt-supervise.sh
  Agent Shipper:      http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/nt-ship.py
  Stats Protocol:     http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/AGENT-STATS-PROTOCOL.md

Telemetry Hub:
  Dashboard & API:    http://{hub_host}:{HUB_PORT}/
  Agent Fleet UI:     http://{hub_host}:{HUB_PORT}/agent-stats
  Agent Stats API:    http://{hub_host}:{HUB_PORT}/api/agent/stats
"""
            return self._reply_text(200, help_text)

        # Oldkernel dedicated bootstrap script (one-line installer)
        if path in ("/oldkernel/bootstrap", "/oldkernel/bootstrap.sh", "/oldkernel/install", "/oldkernel/install.sh", "/bootstrap-oldkernel") or (path in ("/bootstrap", "/bootstrap.sh") and is_oldkernel_query):
            hub_host = self._get_hub_host()
            if not hub_host or not PUBLIC_URL.startswith("https://"):
                return self._reply_text(400, "A valid Host and HTTPS BOOTSTRAP_PUBLIC_URL are required\n")
            installer = os.path.join(PARENT_DIR, "oldkernel", "install-firstrun-el68.sh")
            script = generate_oldkernel_bootstrap_script(hub_host, BOOTSTRAP_PORT, HUB_PORT, PUBLIC_URL, _sha256_file(installer))
            return self._reply_text(200, script, content_type="text/x-shellscript; charset=utf-8")

        # Standard modern bootstrap shell script
        if path in ("/bootstrap", "/bootstrap.sh"):
            hub_host = self._get_hub_host()
            if not hub_host or not PUBLIC_URL.startswith("https://"):
                return self._reply_text(400, "A valid Host and HTTPS BOOTSTRAP_PUBLIC_URL are required\n")
            tar_file = ensure_bundle_tar()
            script = generate_bootstrap_script(hub_host, BOOTSTRAP_PORT, HUB_PORT, PUBLIC_URL, _sha256_file(tar_file))
            return self._reply_text(200, script, content_type="text/x-shellscript; charset=utf-8")

        # Raw install.sh
        if path == "/install.sh":
            install_sh_path = os.path.join(BUNDLE_SRC_DIR, "install.sh")
            if not os.path.exists(install_sh_path):
                install_sh_path = os.path.join(PARENT_DIR, "install.sh")
            if os.path.isfile(install_sh_path):
                try:
                    with open(install_sh_path, "r", encoding="utf-8") as f:
                        return self._reply_text(200, f.read(), content_type="text/x-shellscript; charset=utf-8")
                except Exception as e:
                    return self._reply_text(500, f"Error reading install.sh: {e}")
            return self._reply_text(404, "install.sh not found")

        # Complete bundle tarball
        if path == "/bundle.tar.gz":
            tar_file = ensure_bundle_tar()
            if not tar_file or not os.path.isfile(tar_file):
                return self._reply_text(503, "Bundle not available or packaging failed\n")
            try:
                size = os.path.getsize(tar_file)
                self.send_response(200)
                self.send_header("Content-Type", "application/gzip")
                self.send_header("Content-Length", str(size))
                self.send_header("Content-Disposition", "attachment; filename=\"bundle.tar.gz\"")
                self.send_header("Connection", "close")
                self.end_headers()

                if not getattr(self, "_is_head", False):
                    with open(tar_file, "rb") as f:
                        while True:
                            chunk = f.read(65536)
                            if not chunk:
                                break
                            self.wfile.write(chunk)
                return
            except Exception as e:
                print(f"[nt-bootstrap] Error serving bundle.tar.gz: {e}", file=sys.stderr, flush=True)
                return

        # Old-kernel kit index or files (CentOS 6.x / 2.6.32): /oldkernel or /oldkernel/<name>
        if path == "/oldkernel":
            hub_host = self._get_hub_host()
            oldkernel_dir = os.path.join(PARENT_DIR, "oldkernel")
            files = sorted([
                f for f in os.listdir(oldkernel_dir)
                if os.path.isfile(os.path.join(oldkernel_dir, f)) and not f.startswith(".")
            ]) if os.path.isdir(oldkernel_dir) else []
            lines = [
                f"NetworkTracing Old-kernel Kit Distribution (CentOS 6.x / 2.6.32)",
                f"Source: http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/",
                "============================================================",
                "",
                "One-Line Installation (run on target CentOS 6.x node):",
                f"  curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/bootstrap | sudo sh",
                "",
                "Preflight check only (dry-run):",
                f"  curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/bootstrap | sudo sh -s -- --check",
                "",
                "Clean uninstall:",
                f"  curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/bootstrap | sudo sh -s -- --uninstall",
                "",
                "Available Kit Files:",
            ]
            for f in files:
                sz = os.path.getsize(os.path.join(oldkernel_dir, f))
                lines.append(f"  - http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/{f:<30} ({sz} bytes)")
            lines.append("")
            lines.append("Quick fetch one-liner:")
            lines.append(f"  for f in {' '.join(files[:6])}; do curl -sSf http://{hub_host}:{BOOTSTRAP_PORT}/oldkernel/$f -o $f; done\n")
            return self._reply_text(200, "\n".join(lines))

        if path.startswith("/oldkernel/"):
            name = os.path.basename(path[len("/oldkernel/"):])
            if not name:
                return self._reply_text(404, "filename required\n")

            MIME_MAP = {
                ".sh": "text/x-shellscript; charset=utf-8",
                ".py": "text/x-python; charset=utf-8",
                ".cpp": "text/x-c++; charset=utf-8",
                ".cc": "text/x-c++; charset=utf-8",
                ".c": "text/x-c; charset=utf-8",
                ".h": "text/x-c; charset=utf-8",
                ".hpp": "text/x-c++; charset=utf-8",
                ".md": "text/markdown; charset=utf-8",
                ".json": "application/json; charset=utf-8",
                ".txt": "text/plain; charset=utf-8",
            }
            OK_FILES = {
                "install-oldkernel.sh": "text/x-shellscript; charset=utf-8",
                "el68-smoke.sh": "text/x-shellscript; charset=utf-8",
                "nt-sniff.py": "text/x-python; charset=utf-8",
                "nt-ship.py": "text/x-python; charset=utf-8",
                "nt-control.py": "text/x-python; charset=utf-8",
                "nt_control.py": "text/x-python; charset=utf-8",
                "nt-resource-guard.sh": "text/x-shellscript; charset=utf-8",
                "nt-supervise.sh": "text/x-shellscript; charset=utf-8",
                "nt-test.py": "text/x-python; charset=utf-8",
                "nt-test.sh": "text/x-shellscript; charset=utf-8",
                "measure_usage.py": "text/x-python; charset=utf-8",
                "run_100tps_benchmark.py": "text/x-python; charset=utf-8",
                "pcap_test_cpp.cpp": "text/x-c++; charset=utf-8",
                "test-instruction.md": "text/markdown; charset=utf-8",
                "test_nt_control.py": "text/x-python; charset=utf-8",
                "test_nt_ship.py": "text/x-python; charset=utf-8",
                "test_nt_sniff.py": "text/x-python; charset=utf-8",
                "test_pcap_suite.py": "text/x-python; charset=utf-8",
                "test_resource_guard.py": "text/x-python; charset=utf-8",
                "README.md": "text/markdown; charset=utf-8",
                "DEBUG-NOTES.md": "text/markdown; charset=utf-8",
                "CENTOS-6.7-TEST.md": "text/markdown; charset=utf-8",
                "install-firstrun-el68.sh": "text/x-shellscript; charset=utf-8",
                "build-firstrun.sh": "text/x-shellscript; charset=utf-8",
                "nt-sniff-cpp.cpp": "text/x-c++; charset=utf-8",
                "nt-ship-cpp.cpp": "text/x-c++; charset=utf-8",
                "nt-sniff-mock.cpp": "text/x-c++; charset=utf-8",
                "nt-sniff-cpp": "application/octet-stream",
                "nt-ship-cpp": "application/octet-stream",
                "Makefile": "text/plain; charset=utf-8",
                "cpp-e2e.sh": "text/x-shellscript; charset=utf-8",
                "cpp-edge-test.py": "text/x-python; charset=utf-8",
                "nt-run-cpp.sh": "text/x-shellscript; charset=utf-8",
                "verify-centos-runbook.sh": "text/x-shellscript; charset=utf-8",
                "ANSIBLE.md": "text/markdown; charset=utf-8",
                "RUNNING.md": "text/markdown; charset=utf-8",
                "HOW-TO-USE.md": "text/markdown; charset=utf-8",
                "test_installer_cli.py": "text/x-python; charset=utf-8",
                # Agent Statistics Protocol v1 — new
                "AGENT-STATS-PROTOCOL.md": "text/markdown; charset=utf-8",
                "AGENTS.md": "text/markdown; charset=utf-8",
                "STATE.md": "text/markdown; charset=utf-8",
            }
            content_type = OK_FILES.get(name)
            if not content_type:
                _, ext = os.path.splitext(name)
                content_type = MIME_MAP.get(ext, "application/octet-stream")

            fp = os.path.join(PARENT_DIR, "oldkernel", name)
            if not os.path.isfile(fp):
                return self._reply_text(404, f"oldkernel file missing on hub: {name}\n")
            try:
                with open(fp, "rb") as f:
                    data = f.read()
                self.send_response(200)
                self.send_header("Content-Type", content_type)
                self.send_header("Content-Length", str(len(data)))
                self.send_header("Connection", "close")
                self.end_headers()
                if not getattr(self, "_is_head", False):
                    self.wfile.write(data)
                return
            except Exception as e:
                return self._reply_text(500, f"Error reading {name}: {e}")

        return self._reply_text(404, "Not Found\n")


def run_server():
    ensure_bundle_tar()
    server_address = ("0.0.0.0", BOOTSTRAP_PORT)
    httpd = ThreadingHTTPServer(server_address, BootstrapHandler)
    print(f"[nt-bootstrap] Server listening on 0.0.0.0:{BOOTSTRAP_PORT} (Hub port: {HUB_PORT})", flush=True)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        httpd.server_close()
        print("[nt-bootstrap] Server stopped.", flush=True)


if __name__ == "__main__":
    run_server()
