/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        card: '12px',
        inner: '9px',
        ctl: '8px',
      },
      boxShadow: {
        subtle: '0 0 0 1px var(--border)',
        panel: '0 1px 3px 0 rgba(0, 0, 0, 0.05)',
        card: 'var(--shadow)',
        pop: 'var(--shadow-pop)',
      },
      colors: {
        page: 'var(--page)',
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        line: 'var(--border)',
        'line-strong': 'var(--border-strong)',
        ink: 'var(--text)',
        muted: 'var(--muted)',
        faint: 'var(--faint)',
        accent: 'var(--accent)',
        'accent-soft': 'var(--accent-soft)',
        'accent-2': 'var(--accent-2)',
        info: 'var(--info)',
        'info-bg': 'var(--info-bg)',
        'info-bd': 'var(--info-bd)',
        good: 'var(--good)',
        'good-bg': 'var(--good-bg)',
        'good-bd': 'var(--good-bd)',
        bad: 'var(--bad)',
        'bad-bg': 'var(--bad-bg)',
        'bad-bd': 'var(--bad-bd)',
        warn: 'var(--warn)',
        'warn-bg': 'var(--warn-bg)',
        'warn-bd': 'var(--warn-bd)',
        grid: 'var(--grid)',
        hover: 'var(--hover)',
        selected: 'var(--selected)',
        'path-highlight': 'var(--path-highlight)',
        entity: {
          service: 'var(--entity-service)',
          user: 'var(--entity-user)',
          api: 'var(--entity-api)',
          ip: 'var(--entity-ip)',
        },
        http: {
          '2xx': 'var(--http-2xx)',
          '3xx': 'var(--http-3xx)',
          '4xx': 'var(--http-4xx)',
          '5xx': 'var(--http-5xx)',
        },
      },
    },
  },
  plugins: [],
}
