apiVersion: v1
kind: Service
metadata:
  name: tracescope-clickhouse
  namespace: tracescope
  labels:
    app.kubernetes.io/name: tracescope
    app.kubernetes.io/component: clickhouse
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tracescope
    app.kubernetes.io/component: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: native
      port: 9000
      targetPort: 9000
      protocol: TCP
