apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracescope-ingest
  namespace: tracescope
  labels:
    app.kubernetes.io/name: tracescope
    app.kubernetes.io/component: ingest
    app.kubernetes.io/part-of: tracescope
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tracescope
      app.kubernetes.io/component: ingest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracescope
        app.kubernetes.io/component: ingest
        app.kubernetes.io/part-of: tracescope
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: tracescope
              app.kubernetes.io/component: ingest
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ingest
          image: xhatsu101/tracescope:ingest-0.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: tracescope-config
            - secretRef:
                name: tracescope-secrets
          env:
            - name: OTEL_RUN_MIGRATIONS
              value: "false"
          startupProbe:
            httpGet:
              path: /livez
              port: http
            periodSeconds: 2
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: "2"
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
