CREATE INDEX IF NOT EXISTS idx_mb_size_start ON metric_buckets(bucket_size, bucket_start);
CREATE INDEX IF NOT EXISTS idx_mb_size_start_target ON metric_buckets(bucket_size, bucket_start, target_service);
CREATE INDEX IF NOT EXISTS idx_mb_size_start_principal ON metric_buckets(bucket_size, bucket_start, principal_name);
CREATE INDEX IF NOT EXISTS idx_mb_caller_target_size ON metric_buckets(caller_service, target_service, bucket_size, bucket_start);
CREATE INDEX IF NOT EXISTS idx_mb_principal_target_size ON metric_buckets(principal_name, target_service, bucket_size, bucket_start);
CREATE INDEX IF NOT EXISTS idx_traces_ts_id ON traces(timestamp_ms, id);
CREATE INDEX IF NOT EXISTS idx_traces_span_unique ON traces(trace_id, span_id);
CREATE INDEX IF NOT EXISTS idx_traces_target_ts ON traces(target_service, timestamp_ms);
CREATE INDEX IF NOT EXISTS idx_traces_caller_ts ON traces(caller_service, timestamp_ms);
CREATE INDEX IF NOT EXISTS idx_traces_instance ON traces(service_instance);
