import { useState } from 'react';
import { BehaviorGraph } from './BehaviorGraph';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Network, Search, ShieldCheck, Sparkles } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../api';
import { ErrorState, Loading, Page, Panel, n } from '../components';
import { EntityLink } from '../components/EntityLink';
import { useI18n } from '../i18n';
import { useFilters } from '../App';
import { formatEpisodeTime, type SemanticAssessment } from '../components/EpisodePrimitives';

type Contract = { event_id: string; relationship_id?: string; state: string; reason?: string; reviewer?: string; effective_at_ms?: number; expires_at_ms?: number; created_at?: number; expired?: boolean };
type Profile = {
  id: string; relationship_id?: string; source: string; environment: string; caller: string; principal: string; target: string; operation: string;
  version: string; familiarity: string; quality: string; first_seen: number; last_seen: number; requests: number; errors: number;
  active_days: number; active_windows: number; reference_windows: number; share: number; caller_coverage: number;
  auth_failures: number; auth_successes: number; request_bytes: number; response_bytes: number; byte_samples: number;
  median_active_window_requests: number | null; mad_active_window_requests: number | null; schedule_ready: boolean;
  hourly_windows: number[]; contract: Contract; contracts?: Contract[]; evidence: string[]; evidence_expired?: boolean;
  history: { day: number; requests: number; errors: number; max_bucket_p95_ms: number }[];
  series?: { bucket_ms: number; requests: number; errors: number; p95_ms: number; quality_reason: string }[];
  prior_days: number; prior_requests: number; prior_relationships: string[]; prior_relationship_count: number;
  observed_ips: { address: string; role: string }[];
  graph_features: { credential_target_fanout: number; credential_api_fanout: number; credential_caller_fanout: number; new_caller_for_credential: boolean; new_api_for_credential: boolean };
  tps: { latest: number|null; latest_at: number; baseline: number|null; mad: number|null; ready: boolean; fresh: boolean; persistent_surge: boolean; reference_windows: number; hourly_baselines: (number|null)[] };
  graph_learning?: { strength:number; observed_windows:number; rate_samples:number; withheld_rate_windows:number; expected_tps:number; last_score:{expected_tps:number|null;tps_surprise:number|null} };
  kind?: string; status?: string; persistent?: boolean; baseline_ready?: boolean; severity?: string;
  semantic_assessment?: SemanticAssessment; trace_search_url?: string;
};
type Collection<T> = { items: T[]; total: number };
type Coverage = { source: string; mode?: string; error?: string; materialized_days: number; through_ms?: number; published_at?: number; requests: number; identified_requests: number; caller_observed_requests: number; known_environment_requests: number; pending?: { day: number; pages: number } };
type Overview = { mode: string; enabled: boolean; profiles: number; established: number; unreviewed: number; approved: number; coverage: Coverage[] };
const endpoint = '/api/v1/behavior';

function useLabels() {
  const { t } = useI18n();
  const labels: Record<string, string> = {
    legacy_metrics: t('Legacy metrics · environment unknown', 'Metric lịch sử · chưa rõ môi trường'),
    emerging: t('Emerging', 'Đang học'),
    established: t('Established', 'Đã ổn định'), dormant: t('Dormant', 'Không hoạt động gần đây'),
    unreviewed: t('Unreviewed', 'Chưa duyệt'), reviewed: t('Reviewed', 'Đã duyệt'), approved: t('Approved', 'Đã chấp thuận'),
    temporary: t('Temporary approval', 'Chấp thuận tạm thời'), prohibited: t('Prohibited', 'Không được phép'),
    traffic_surge: t('Persistent TPS surge', 'TPS tăng kéo dài'),
    graph_tps_shift: t('Learned TPS deviation', 'TPS lệch mức đã học'), graph_edge_novelty: t('New learned relationship', 'Quan hệ mới trong đồ thị học'),
    access_expansion: t('Access expansion', 'Mở rộng truy cập'), contract_violation: t('Contract violation', 'Vi phạm phạm vi chấp thuận'),
    unknown: t('Unknown', 'Chưa rõ'), limited: t('Limited attribution', 'Thông tin quy thuộc hạn chế'), observed: t('Observed attribution', 'Có thông tin quy thuộc'),
    backfill: t('Learning history', 'Đang học lịch sử'), live: t('Updating', 'Đang cập nhật'),
  };
  return (key: string) => labels[key] || key;
}
function Badge({ value }: { value: string }) {
  const label = useLabels();
  const tone = value === 'prohibited' || value === 'contract_violation' ? 'text-[#f2495c] border-[#f2495c]/40' : value === 'approved' || value === 'established' ? 'text-[#73bf69] border-[#73bf69]/40' : 'text-[#a7a9ab] border-[#34373b]';
  return <span className={`inline-flex border px-2 py-1 text-[11px] ${tone}`}>{label(value)}</span>;
}
function PathLabel({ item }: { item: Profile }) {
  const { t } = useI18n();
  return <div className="min-w-0 space-y-1"><div className="flex flex-wrap items-center gap-1.5 text-xs"><span className="break-all text-[#5794f2]">{item.caller}</span><ArrowRight size={12} aria-hidden="true" /><span className="break-all text-[#5794f2]">{item.target}</span><ArrowRight size={12} aria-hidden="true" /><span className="break-all text-[#56b9a8]">{item.operation}</span></div><div className="break-all text-[11px] text-[#a7a9ab]">{t('Observed credential', 'Credential quan sát')}: <span className="text-[#b877d9]">{item.principal}</span> · {item.environment}</div></div>;
}

export function BehaviorPage() {
  const { t } = useI18n(); const label = useLabels(); const { filters } = useFilters();
  const [params, setParams] = useSearchParams();
  const tab = ['overview','graph','profiles','deviations','contracts'].includes(params.get('tab') || '') ? params.get('tab')! : 'overview';
  const offset = Math.max(0, Number(params.get('offset')) || 0);
  const overview = useQuery({ queryKey: ['behavior-overview'], queryFn: () => api<Overview>(`${endpoint}/overview`), refetchInterval: 60000 });
  const query = new URLSearchParams({ limit: '25', offset: String(offset) });
  for (const key of ['q','source','environment','state']) if (params.get(key)) query.set(key, params.get(key)!);
  const list = useQuery({ queryKey: ['behavior-list', tab, query.toString()], queryFn: () => api<Collection<Profile & Contract>>(`${endpoint}/${tab}?${query}`), enabled: tab !== 'overview' && tab !== 'graph', refetchInterval: 60000 });
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key,value) : next.delete(key); if (key !== 'offset') next.delete('offset'); setParams(next); };
  return <Page title={t('Learned behavior', 'Hành vi đã học')} eyebrow={t('Behavioral memory', 'Bộ nhớ hành vi')} description={t('Observed relationships, historical deviations and scoped approvals. Sources remain separate.', 'Quan hệ quan sát, biến động lịch sử và phạm vi chấp thuận. Các nguồn được giữ riêng biệt.')}>
    <div className="mb-4 flex flex-wrap items-center gap-2 border border-[#34373b] bg-[#111217] p-3 text-xs text-[#a7a9ab]"><Network size={15} className="text-[#5794f2]" aria-hidden="true" /><strong>{t('Shadow learning', 'Học ở chế độ quan sát')}</strong><span>{t('Uses its own learning window. No network enforcement or notification changes.', 'Dùng cửa sổ học riêng. Không chặn truy cập hoặc thay đổi thông báo.')}</span></div>
    <nav aria-label={t('Behavior sections', 'Các mục hành vi')} className="mb-4 flex flex-wrap gap-2">{[['overview',t('Overview','Tổng quan')],['graph',t('Learning graph','Đồ thị học')],['profiles',t('Profiles','Hồ sơ')],['deviations',t('Deviations','Biến động')],['contracts',t('Contracts','Phạm vi chấp thuận')]].map(([key,text]) => <button key={key} type="button" onClick={() => update('tab',key)} aria-current={tab===key?'page':undefined} className={`btn ${tab===key?'border-[#5794f2] text-[#5794f2]':''}`}>{text}</button>)}</nav>
    {tab==='overview' ? overview.isLoading ? <Loading /> : overview.error ? <ErrorState message={overview.error.message} /> : overview.data && <>
      <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[t('Relationships','Quan hệ'),overview.data.profiles],[t('Established','Đã ổn định'),overview.data.established],[t('Unreviewed deviations','Biến động chưa duyệt'),overview.data.unreviewed],[t('Approved','Đã chấp thuận'),overview.data.approved]].map(([name,value]) => <div key={name} className="panel p-4"><div className="text-xs text-[#a7a9ab]">{name}</div><div className="mt-2 font-mono text-2xl text-[#d8d9da]">{value}</div></div>)}</div>
      <Panel title={t('Learning coverage','Độ phủ dữ liệu học')} subtitle={t('Successful materialization does not prove complete collection. Sampling coverage is unknown.', 'Tổng hợp thành công không chứng minh dữ liệu thu thập đầy đủ. Chưa xác định tỷ lệ lấy mẫu.')}><div className="divide-y divide-[#2a2d30]">{overview.data.coverage.map(c => <div key={c.source} className="grid gap-3 p-4 md:grid-cols-3"><div><div className="text-sm text-[#d8d9da]">{label(c.source)}</div><div className="mt-1 text-xs text-[#a7a9ab]">{c.error ? t('Update failed; last snapshot retained','Cập nhật lỗi; giữ bản đã lưu') : label(c.mode || 'emerging')}</div>{c.pending && <div className="mt-1 text-xs text-[#a7a9ab]">{t('Processing day','Đang xử lý ngày')}: {formatEpisodeTime(c.pending.day,true,filters.timezone)} · {c.pending.pages} {t('pages','trang')}</div>}</div><div className="text-xs leading-6 text-[#a7a9ab]">{c.materialized_days} {t('materialized days','ngày đã tổng hợp')} · {n(c.requests)} {t('requests','request')}<br />{t('Through','Đến')}: {c.through_ms?formatEpisodeTime(c.through_ms,true,filters.timezone):'—'}</div><div className="text-xs leading-6 text-[#a7a9ab]">{t('Credential / Caller / Environment observed','Có Credential / Caller / Môi trường')}:<br />{[c.identified_requests,c.caller_observed_requests,c.known_environment_requests].map(v=>c.requests?`${Math.round(v/c.requests*100)}%`:'—').join(' / ')}</div></div>)}</div></Panel>
      <Panel className="mt-4" title={t('How learning works','Cách hệ thống học')}><div className="space-y-2 p-4 text-sm leading-6 text-[#a7a9ab]"><p>{t('An exact caller, credential, target and API combination is compared with earlier history in the same source and environment. Repetition establishes familiarity, never approval.', 'Tổ hợp Caller, Credential, Service đích và API được so sánh với lịch sử trước đó trong cùng nguồn và môi trường. Lặp lại tạo sự quen thuộc, không tự động chấp thuận.')}</p><p>{t('Each completed five-minute window reinforces observed nodes and edges. Older support decays; traffic surprise is scored against a learned reference before updating it. IPs remain observed peers.', 'Mỗi cửa sổ năm phút hoàn tất củng cố nút và cạnh quan sát. Trọng số cũ giảm dần; mức bất ngờ lưu lượng được tính với tham chiếu đã học trước khi cập nhật. IP vẫn là địa chỉ quan sát.')}</p><p>{t('Five-minute observations: 30 days. Daily memory: 90 days. Recent two days refresh for late arrivals. Older arrivals require replay. Raw trace retention is unchanged.', 'Quan sát năm phút: 30 ngày. Bộ nhớ theo ngày: 90 ngày. Hai ngày gần nhất được cập nhật cho dữ liệu đến muộn. Dữ liệu cũ hơn cần chạy lại. Giữ nguyên thời hạn lưu Trace gốc.')}</p></div></Panel>
    </> : tab==='graph' ? <BehaviorGraph/> : <>
      {tab!=='contracts' && <div className="mb-3 flex flex-wrap gap-2"><label className="flex min-w-0 flex-1 items-center gap-2 border border-[#34373b] bg-[#181b1f] px-3"><Search size={14} aria-hidden="true" /><input aria-label={t('Search relationships','Tìm quan hệ')} value={params.get('q')||''} onChange={e=>update('q',e.target.value)} placeholder={t('Service, API, credential…','Service, API, credential…')} className="min-w-0 w-full bg-transparent py-2 text-xs outline-none" /></label><select aria-label={t('Source','Nguồn')} className="btn max-w-full" value={params.get('source')||''} onChange={e=>update('source',e.target.value)}><option value="">{t('All sources','Tất cả nguồn')}</option>{['legacy_metrics'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select><select aria-label={t('State','Trạng thái')} className="btn" value={params.get('state')||''} onChange={e=>update('state',e.target.value)}><option value="">{t('All states','Tất cả trạng thái')}</option>{(tab==='profiles'?['emerging','established','dormant','approved','temporary','prohibited','unreviewed']:['unreviewed','reviewed','access_expansion','contract_violation','traffic_surge','graph_tps_shift','graph_edge_novelty']).map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div>}
      {list.isLoading?<Loading />:list.error?<div><ErrorState message={list.error.message}/><button className="btn" onClick={()=>list.refetch()}>{t('Retry','Thử lại')}</button></div>:<Panel title={t('Results','Kết quả')}><div className="divide-y divide-[#2a2d30]">{!list.data?.items.length?<div className="p-8 text-center text-sm text-[#a7a9ab]">{t('No results. Learning may still be collecting history; try another filter.', 'Chưa có kết quả. Hệ thống có thể đang học lịch sử; hãy thử bộ lọc khác.')}</div>:list.data.items.map(item=>tab==='contracts'?<div key={item.event_id} className="space-y-2 p-4"><div className="flex flex-wrap items-center gap-2"><Badge value={item.state}/><span className="text-xs text-[#a7a9ab]">{item.reviewer} · {formatEpisodeTime(item.effective_at_ms||0,true,filters.timezone)}</span><Link className="text-xs text-[#5794f2] underline" to={`/behavior/profiles/${item.relationship_id}`}>{t('View relationship','Xem quan hệ')}</Link></div><p className="break-words text-xs text-[#d8d9da]">{item.reason}</p>{!!item.expires_at_ms&&<p className="text-xs text-[#a7a9ab]">{t('Expires','Hết hạn')}: {formatEpisodeTime(item.expires_at_ms,true,filters.timezone)}</p>}</div>:<Link key={item.id} to={`/behavior/${tab}/${item.id}`} className="block space-y-2 p-4 hover:bg-[#181b1f] focus-visible:outline focus-visible:outline-[#5794f2]"><PathLabel item={item}/><div className="flex flex-wrap items-center gap-2"><Badge value={item.kind||item.familiarity}/><Badge value={item.contract.state}/><span className="text-[11px] text-[#a7a9ab]">{label(item.source)} · {item.active_days} {t('days','ngày')} · {item.active_windows} {t('windows','cửa sổ')} · {n(item.requests)} request · {item.tps?.latest!=null?n(item.tps.latest,4):'—'} TPS</span></div></Link>)}</div></Panel>}
      <div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-[#a7a9ab]"><span>{Math.min(offset+(list.data?.items.length?1:0),list.data?.total||0)}–{offset+(list.data?.items.length||0)} / {list.data?.total||0}</span><div className="flex gap-2"><button className="btn" disabled={!offset} onClick={()=>update('offset',String(Math.max(0,offset-25)))}>{t('Previous','Trước')}</button><button className="btn" disabled={offset+25>=(list.data?.total||0)} onClick={()=>update('offset',String(offset+25))}>{t('Next','Tiếp')}</button></div></div>
    </>}
  </Page>;
}

function TpsPanel({item}:{item:Profile}) {
  const {t}=useI18n(); const {filters}=useFilters();
  const day=Math.floor(item.last_seen/86400000)*86400000;
  const observed=new Map((item.series||[]).map(r=>[r.bucket_ms,r.requests/300]));
  const points=Array.from({length:Math.floor((item.last_seen-day)/300000)+1},(_,i)=>{
    const at=day+i*300000;return {at,tps:observed.get(at)??null,baseline:item.tps?.hourly_baselines?.[Math.floor(at/3600000)%24]??null};
  });
  const peak=Math.max(0,...points.flatMap(p=>[p.tps||0,p.baseline||0]));
  return <Panel className="mb-4" title={t('Relationship TPS','TPS theo quan hệ')} subtitle={t('Latest observed day · five-minute buckets · Baseline from earlier days at the same UTC hour. Gaps remain unknown.', 'Ngày quan sát gần nhất · bucket năm phút · Baseline từ các ngày trước cùng giờ UTC. Khoảng trống là chưa rõ.')}>
    <div className="grid gap-3 border-b border-[#2a2d30] p-3 sm:grid-cols-3">{[[t('Last observed TPS','TPS quan sát cuối'),item.tps?.latest],[t('Historical TPS','TPS lịch sử'),item.tps?.baseline],[t('MAD · TPS','MAD · TPS'),item.tps?.mad]].map(([label,value])=><div key={String(label)}><div className="text-[11px] text-[#a7a9ab]">{label}</div><div className="mt-1 font-mono text-lg text-[#5794f2]">{value==null?'—':n(Number(value),4)}</div></div>)}</div>
    <div className="h-60 p-3">{item.series===undefined?<Loading/>:<ResponsiveContainer width="100%" height="100%"><LineChart data={points}><CartesianGrid stroke="#303236" vertical={false}/><XAxis dataKey="at" tickFormatter={v=>formatEpisodeTime(v,false,filters.timezone)} tick={{fill:'#a7a9ab',fontSize:11}}/><YAxis domain={[0,peak||1]} width={60} tick={{fill:'#a7a9ab',fontSize:11}} tickFormatter={v=>n(v,3)}/><Tooltip contentStyle={{background:'#111217',border:'1px solid #34373b'}} labelFormatter={v=>formatEpisodeTime(Number(v),true,filters.timezone)} formatter={(v:unknown,name:unknown)=>[`${n(Number(v),4)} TPS`,String(name)]}/><Line dataKey="tps" name="TPS" stroke="#5794f2" dot={false} connectNulls={false} isAnimationActive={false}/><Line dataKey="baseline" name="Baseline" stroke="#a7a9ab" strokeDasharray="4 4" dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer>}</div>
    <div className="flex flex-wrap gap-3 border-t border-[#2a2d30] p-3 text-[11px] text-[#a7a9ab]"><span className="text-[#5794f2]">━ TPS</span><span>┄ Baseline</span><span>{item.tps?.ready?t('Baseline ready','Baseline sẵn sàng'):t('Baseline still learning','Baseline đang học')}</span>{!item.tps?.fresh&&<span>{t('Historical observation; not current traffic','Quan sát lịch sử; không phải lưu lượng hiện tại')}</span>}</div>
  </Panel>;
}

function RelationshipGraph({ item }: { item: Profile }) {
  const { t } = useI18n(); const [selected,setSelected]=useState('api');
  const nodes=[{id:'caller',label:t('Caller Service','Service gọi'),value:item.caller,color:'#5794f2'},
    {id:'api',label:t('Target API','API đích'),value:item.operation,color:'#56b9a8'},
    {id:'credential',label:t('Observed credential','Credential quan sát'),value:item.principal,color:'#b877d9'},
    {id:'ip',label:t('Observed IPs','IP quan sát'),value:item.observed_ips.length?item.observed_ips.map(i=>i.address).join(', '):t('Not available','Chưa có'),color:'#a7a9ab'}];
  return <Panel title={t('Relationship graph','Đồ thị quan hệ')} subtitle={t('Select a node. Credential and IP are evidence attached to the observed interaction.', 'Chọn một nút. Credential và IP là bằng chứng gắn với tương tác quan sát.')}><div className="p-4"><div className="mb-3 flex items-center gap-3 text-[11px] text-[#a7a9ab]"><span className="block w-16 border-[#5794f2]" style={{borderTopWidth:Math.min(7,1+Math.log2(1+(item.tps?.latest||0)))}}/><span>{item.tps?.latest!=null?n(item.tps.latest,4):'—'} TPS · {t('last observed call rate','tốc độ gọi quan sát cuối')}</span></div><svg viewBox="0 0 720 270" className="mb-4 hidden w-full md:block" role="group" aria-label={t('Observed relationship graph','Đồ thị quan hệ quan sát')}>
      <defs><marker id="behavior-call-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="#5794f2"/></marker></defs>
      <path d="M205 65 H270" fill="none" stroke="#5794f2" strokeWidth={Math.min(6,1+Math.log2(1+(item.tps?.latest||0)))} markerEnd="url(#behavior-call-arrow)"/><text x="237" y="49" textAnchor="middle" fill="#a7a9ab" fontSize="10">{t('calls','gọi')}</text>
      <path d="M505 65 H440" fill="none" stroke="#5794f2" strokeWidth="1"/><text x="474" y="49" textAnchor="middle" fill="#a7a9ab" fontSize="10">{t('owns','sở hữu')}</text>
      <path d="M355 105 V165" fill="none" stroke="#b877d9" strokeDasharray="4 4"/><text x="365" y="137" fill="#a7a9ab" fontSize="10">{t('credential observed','credential quan sát')}</text>
      <path d="M605 165 V130 H440 V100" fill="none" stroke="#a7a9ab" strokeDasharray="4 4"/><text x="565" y="150" fill="#a7a9ab" fontSize="10">{t('peer observed','IP quan sát')}</text>
      {[{...nodes[0],x:5,y:25},{...nodes[1],x:255,y:25},{id:'target',label:t('Target Service','Service đích'),value:item.target,color:'#5794f2',x:505,y:25},{...nodes[2],x:255,y:170},{...nodes[3],x:505,y:170}].map(node=><g key={node.id} role="button" tabIndex={0} aria-label={`${node.label}: ${node.value}`} aria-pressed={selected===node.id} onClick={()=>setSelected(node.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(node.id);}}} className="cursor-pointer focus-visible:outline focus-visible:outline-[#5794f2]"><title>{node.label}: {node.value}</title><rect x={node.x} y={node.y} width="195" height="80" rx="2" fill={selected===node.id?'#181b1f':'#111217'} stroke={selected===node.id?node.color:'#34373b'}/><text x={node.x+12} y={node.y+23} fill={node.color} fontSize="11">{node.label}</text><text x={node.x+12} y={node.y+49} fill="#d8d9da" fontSize="10">{node.value.length>25?node.value.slice(0,24)+'…':node.value}</text></g>)}
    </svg><div className="grid items-stretch gap-3 md:hidden">{nodes.map((node,index)=><div key={node.id} className="min-w-0"><button type="button" aria-pressed={selected===node.id} onClick={()=>setSelected(node.id)} className={`h-full w-full min-w-0 border p-3 text-left ${selected===node.id?'bg-[#181b1f]':'border-[#34373b]'}`} style={selected===node.id?{borderColor:node.color}:undefined}><div className="mb-2 flex items-center justify-between text-[11px]" style={{color:node.color}}><span>{node.label}</span><Network size={13} aria-hidden="true"/></div><div className="break-all font-mono text-xs text-[#d8d9da]">{node.value}</div><div className="mt-2 text-[10px] text-[#7b7d80]">{index===0?t('calls target API →','gọi API đích →'):index===1?t('belongs to target service','thuộc Service đích'):t('observed on this interaction','quan sát trong tương tác này')}</div></button></div>)}</div><div className="mt-3 border-t border-[#2a2d30] pt-3 text-xs leading-6 text-[#a7a9ab]">{(selected==='api'||selected==='target')?<>{t('Target Service','Service đích')}: <EntityLink entity={{kind:'service',name:item.target}} className="text-[#5794f2]">{item.target}</EntityLink> · <EntityLink entity={{kind:'api',service:item.target,operation:item.operation}} className="text-[#56b9a8]">{t('Open API','Mở API')}</EntityLink></>:selected==='caller'?<EntityLink entity={{kind:'service',name:item.caller}} className="text-[#5794f2]">{t('Open caller Service','Mở Service gọi')}</EntityLink>:selected==='credential'?<EntityLink entity={{kind:'user',principal:item.principal}} className="text-[#b877d9]">{t('Open credential activity','Mở hoạt động credential')}</EntityLink>:<>{t('IPs do not establish a human identity. Infrastructure peers are excluded from source-novelty claims.', 'IP không xác lập danh tính con người. IP hạ tầng không được dùng để kết luận nguồn truy cập mới.')} {item.observed_ips.map(ip=><span key={ip.address} className="mr-2 inline-block">{ip.address}: {ip.role==='infrastructure'?t('Infrastructure','Hạ tầng'):t('Unverified peer','Địa chỉ chưa xác minh')}</span>)}</>}</div></div></Panel>;
}

function ReviewForm({ item }: { item: Profile }) {
  const { t }=useI18n(); const qc=useQueryClient(); const [state,setState]=useState('approved'); const [reason,setReason]=useState(''); const [reviewer,setReviewer]=useState(''); const [hours,setHours]=useState(24);
  const mutation=useMutation({mutationFn:()=>api(`${endpoint}/profiles/${item.id}/contracts`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state,reason,reviewer,expires_at_ms:state==='temporary'?Date.now()+hours*3600000:0,expected_event_id:item.contracts?.[0]?.event_id||''})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['behavior-detail']});qc.invalidateQueries({queryKey:['behavior-overview']});qc.invalidateQueries({queryKey:['behavior-list']});setReason('');}});
  return <Panel title={t('Review this relationship','Duyệt quan hệ này')} subtitle={t('Exact source and environment scope. Decisions classify behavior; they do not enforce access. Reviewer name is operator supplied.', 'Áp dụng đúng nguồn và môi trường. Quyết định phân loại hành vi, không chặn truy cập. Tên người duyệt do operator cung cấp.')}><form className="grid gap-3 p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();mutation.mutate();}}><label className="text-xs text-[#a7a9ab]">{t('Decision','Quyết định')}<select className="mt-1 block w-full border border-[#34373b] bg-[#181b1f] p-2" value={state} onChange={e=>setState(e.target.value)}>{[['approved',t('Approve','Chấp thuận')],['temporary',t('Approve temporarily','Chấp thuận tạm thời')],['prohibited',t('Mark prohibited','Đánh dấu không được phép')],['unreviewed',t('Revoke approval / reopen','Thu hồi / mở lại')]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-xs text-[#a7a9ab]">{t('Reviewer','Người duyệt')}<input required maxLength={120} value={reviewer} onChange={e=>setReviewer(e.target.value)} className="mt-1 block w-full border border-[#34373b] bg-[#181b1f] p-2" /></label>{state==='temporary'&&<label className="text-xs text-[#a7a9ab]">{t('Expires after (hours)','Hết hạn sau (giờ)')}<input type="number" required min={1} max={2160} value={hours} onChange={e=>setHours(Number(e.target.value))} className="mt-1 block w-full border border-[#34373b] bg-[#181b1f] p-2" /></label>}<label className="text-xs text-[#a7a9ab] sm:col-span-2">{t('Reason','Lý do')}<textarea required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 block w-full border border-[#34373b] bg-[#181b1f] p-2" /></label><div className="flex flex-wrap items-center gap-2 sm:col-span-2"><button className="btn border-[#5794f2] text-[#5794f2]" disabled={mutation.isPending}><ShieldCheck size={14}/>{mutation.isPending?t('Saving…','Đang lưu…'):t('Save decision','Lưu quyết định')}</button>{mutation.isSuccess&&<span role="status" className="text-xs text-[#73bf69]">{t('Decision saved','Đã lưu quyết định')}</span>}{mutation.error&&<span role="alert" className="text-xs text-[#f2495c]">{mutation.error.message}</span>}</div></form></Panel>;
}

export function BehaviorDetailPage({ kind }: { kind: 'profiles'|'deviations' }) {
  const { id='' }=useParams(); const {t}=useI18n(); const label=useLabels(); const {filters}=useFilters();
  const detail=useQuery({queryKey:['behavior-detail',kind,id],queryFn:()=>api<Profile>(`${endpoint}/${kind}/${id}`)});
  const related=useQuery({queryKey:['behavior-detail','profiles',detail.data?.relationship_id],queryFn:()=>api<Profile>(`${endpoint}/profiles/${detail.data!.relationship_id}`),enabled:kind==='deviations'&&!!detail.data?.relationship_id});
  if(detail.isLoading)return <Loading/>; if(detail.error||!detail.data)return <ErrorState message={detail.error?.message||t('Profile unavailable','Chưa có hồ sơ')}/>;
  const item=detail.data; const profile=kind==='profiles'?item:related.data; const stats=item.graph_features;
  const recommendation: Record<string,string>={observe:t('Monitor subsequent windows.','Theo dõi các cửa sổ tiếp theo.'),inspect_traces:t('Inspect related Traces.','Kiểm tra Trace liên quan.'),compare_baseline:t('Compare with Baseline.','So sánh với Baseline.'),review_access:t('Review access evidence.','Rà soát bằng chứng truy cập.'),check_dependencies:t('Check dependencies.','Kiểm tra Service phụ thuộc.'),collect_evidence:t('Collect more evidence.','Thu thập thêm bằng chứng.')};
  return <Page description={t('Historical behavior and exact relationship scope.', 'Hành vi lịch sử và phạm vi quan hệ cụ thể.')} title={kind==='deviations'?label(item.kind||'access_expansion'):t('Relationship profile','Hồ sơ quan hệ')} eyebrow={t('Learned behavior','Hành vi đã học')} actions={<Link to={`/behavior?tab=${kind}`} className="btn"><ArrowLeft size={13}/>{t('Back','Quay lại')}</Link>}>
    <section className="panel mb-4 space-y-3 p-4"><PathLabel item={item}/><div className="flex flex-wrap gap-2"><Badge value={item.familiarity}/><Badge value={(profile||item).contract.state}/><Badge value={item.quality}/></div><p className="text-xs text-[#a7a9ab]">{label(item.source)} · {t('First / last observed','Quan sát đầu / cuối')}: {formatEpisodeTime(item.first_seen,true,filters.timezone)} / {formatEpisodeTime(item.last_seen,true,filters.timezone)}</p></section>
    <TpsPanel item={profile||item}/><RelationshipGraph item={item}/>
    {item.graph_learning&&<Panel className="mt-4" title={t('Online learning state','Trạng thái học trực tuyến')}><div className="flex flex-wrap gap-4 p-4 text-xs text-[#a7a9ab]"><span>{t('Relationship strength','Độ mạnh quan hệ')}: {n(item.graph_learning.strength*100,1)}%</span><span>{t('Learned next-window TPS','TPS đã học cho cửa sổ tiếp')}: {item.graph_learning.rate_samples?n(item.graph_learning.expected_tps,4):'—'}</span><span>{t('Reference windows','Cửa sổ tham chiếu')}: {item.graph_learning.rate_samples}</span><span>{t('Withheld from TPS reference','Không đưa vào tham chiếu TPS')}: {item.graph_learning.withheld_rate_windows}</span><span>{t('Latest TPS surprise','Mức bất ngờ TPS cuối')}: {item.graph_learning.last_score.tps_surprise==null?'—':`${n(item.graph_learning.last_score.tps_surprise*100,1)}%`}</span></div></Panel>}
    <div className="my-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[t('Active days / windows','Ngày / cửa sổ có hoạt động'),`${item.active_days} / ${item.active_windows}`],[t('Requests / credential share','Request / tỷ trọng credential'),`${n(item.requests)} / ${n(item.share*100,1)}%`],[t('Target / API fanout','Số Service đích / API'),`${stats.credential_target_fanout} / ${stats.credential_api_fanout}`],[t('Observed callers','Service gọi quan sát'),stats.credential_caller_fanout]].map(([name,value])=><div className="panel p-4" key={name}><div className="text-[11px] text-[#a7a9ab]">{name}</div><div className="mt-2 font-mono text-xl text-[#d8d9da]">{value}</div></div>)}</div>
    {kind==='deviations'&&['traffic_surge','graph_tps_shift'].includes(item.kind||'')&&<Panel title={t('TPS comparison','So sánh TPS')}><div className="p-4 text-sm text-[#a7a9ab]">{t('Historical TPS → last observed TPS','TPS lịch sử → TPS quan sát cuối')}: {n((item.kind==='graph_tps_shift'?item.graph_learning?.last_score.expected_tps:item.tps.baseline)||0,4)} → {n(item.tps.latest||0,4)}. {t('Three contiguous windows exceed both the robust baseline threshold and a material request increase. Access approval does not approve a volume surge.', 'Ba cửa sổ liên tiếp vượt ngưỡng Baseline và mức tăng request đáng kể. Chấp thuận truy cập không chấp thuận lưu lượng tăng đột biến.')}</div></Panel>}
    {kind==='deviations'&&!['traffic_surge','graph_tps_shift','graph_edge_novelty'].includes(item.kind||'')&&<Panel title={t('Before → observed','Trước → quan sát')}><div className="grid gap-4 p-4 sm:grid-cols-2"><div className="text-sm leading-6 text-[#a7a9ab]">{t('Earlier credential history','Lịch sử credential trước đó')}: {item.prior_days} {t('days','ngày')}, {n(item.prior_requests)} request, {item.prior_relationship_count} {t('relationships','quan hệ')}.<p>{t('Comparison excludes the first observed day of this relationship. Novelty is limited to available history.', 'So sánh loại trừ ngày đầu quan sát quan hệ này. Tính mới chỉ áp dụng trong lịch sử hiện có.')}</p></div><div className="text-sm leading-6 text-[#d8d9da]">{t('Current relationship','Quan hệ hiện tại')}: {item.active_windows} {t('windows','cửa sổ')}.<p>{item.persistent?t('Repeated in at least three windows.','Lặp lại trong ít nhất ba cửa sổ.'):t('Persistence is not yet established.','Chưa xác lập tính kéo dài.')}</p><p>{t('New caller / new API for credential','Caller mới / API mới với credential')}: {stats.new_caller_for_credential?t('Yes','Có'):t('No','Không')} / {stats.new_api_for_credential?t('Yes','Có'):t('No','Không')}</p></div></div></Panel>}
    <Panel className="mt-4" title={t('Observed history','Lịch sử quan sát')} subtitle={t('Daily request totals; missing days are unknown, not zero traffic.', 'Tổng request theo ngày; ngày thiếu dữ liệu là chưa rõ, không phải không có lưu lượng.')}><div className="h-64 p-3">{item.history.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={item.history}><CartesianGrid stroke="#303236" vertical={false}/><XAxis dataKey="day" tickFormatter={v=>formatEpisodeTime(v,false,filters.timezone)} tick={{fill:'#a7a9ab',fontSize:11}}/><YAxis width={48} tick={{fill:'#a7a9ab',fontSize:11}}/><Tooltip contentStyle={{background:'#111217',border:'1px solid #34373b'}} labelFormatter={v=>formatEpisodeTime(Number(v),true,filters.timezone)}/><Line dataKey="requests" name={t('Requests','Request')} stroke="#5794f2" dot={false} type="linear" isAnimationActive={false}/></LineChart></ResponsiveContainer>:<p className="text-sm text-[#a7a9ab]">{t('No history available','Chưa có lịch sử')}</p>}</div></Panel>
    <div className="my-4 grid gap-4 lg:grid-cols-2"><Panel title={t('Learning evidence','Bằng chứng học')}><div className="space-y-2 p-4 text-xs leading-6 text-[#a7a9ab]"><p>{t('Eligible reference windows','Cửa sổ tham chiếu đủ điều kiện')}: {item.reference_windows}</p><p>{t('Median / MAD requests per active window','Median / MAD request mỗi cửa sổ có hoạt động')}: {item.median_active_window_requests??'—'} / {item.mad_active_window_requests??'—'}</p><p>{t('Explicit authentication failure / success','Xác thực thất bại / thành công rõ ràng')}: {item.auth_failures} / {item.auth_successes}</p><p>{t('Weekly schedule readiness','Độ sẵn sàng lịch theo tuần')}: {item.schedule_ready?t('Ready','Sẵn sàng'):t('Insufficient history','Chưa đủ lịch sử')}</p><p>{t('Byte samples','Mẫu có số byte')}: {item.byte_samples} · {item.byte_samples?`${n(item.request_bytes+item.response_bytes)} B`:'—'}</p><p>{t('Caller presence measures recorded fields, not verified causality. Collection and sampling completeness remain unknown.', 'Độ phủ Caller đo trường được ghi nhận, không chứng minh quan hệ nhân quả. Chưa xác định độ đầy đủ thu thập và lấy mẫu.')}</p></div></Panel><Panel title={t('Trace evidence','Bằng chứng Trace')}><div className="space-y-2 p-4 text-xs leading-6 text-[#a7a9ab]">{profile?.evidence_expired?<p>{t('Stored Trace examples may have expired. Aggregate facts remain available.', 'Trace mẫu có thể đã hết hạn lưu. Dữ kiện tổng hợp vẫn còn.')}</p>:item.evidence.length?item.evidence.map(id=><Link key={id} className="block break-all text-[#5794f2] underline" to={`/traces/${encodeURIComponent(id)}`}>{id}</Link>):<p>{t('This source has no exact Trace examples. Aggregates do not prove the exact request chain.', 'Nguồn này không có Trace mẫu chính xác. Dữ liệu tổng hợp không chứng minh chuỗi request cụ thể.')}</p>}{profile?.trace_search_url&&<Link className="btn" to={profile.trace_search_url}>{t('Search related Traces','Tìm Trace liên quan')}</Link>}</div></Panel></div>
    {kind==='deviations'&&<Panel className="mb-4" title={t('Jev AI result','Kết quả Jev AI')}><div className="space-y-2 p-4 text-sm text-[#a7a9ab]"><Sparkles size={16} className="text-[#b877d9]" aria-hidden="true"/>{['succeeded','stale'].includes(item.semantic_assessment?.status||'')?<><p>{recommendation[item.semantic_assessment?.recommendation||'collect_evidence']}</p><p>{t('Abnormal probability','Xác suất bất thường')}: {Math.round((item.semantic_assessment?.abnormal_probability||0)*100)}%</p></>:<p>{item.semantic_assessment?.status==='pending'?t('Assessment in progress','Đang đánh giá'):item.semantic_assessment?.status==='failed'?t('Assessment unavailable','Đánh giá không khả dụng'):t('No assessment stored yet','Chưa có đánh giá được lưu')}</p>}{item.semantic_assessment?.status==='stale'&&<p className="text-xs text-[#ff9830]">{t('Previous evidence version; assessment may be outdated.','Phiên bản bằng chứng trước; đánh giá có thể đã cũ.')}</p>}<p className="text-xs">{t('Advisory only. Approval remains an operator decision.', 'Chỉ tham khảo. Chấp thuận vẫn là quyết định của operator.')}</p></div></Panel>}
    {profile?<ReviewForm item={profile}/>:related.error?<ErrorState message={related.error.message}/>:<Loading/>}
    <details className="panel mt-4 p-4 text-xs text-[#a7a9ab]"><summary className="cursor-pointer">{t('Contract history and technical details','Lịch sử chấp thuận và chi tiết kỹ thuật')}</summary><p className="my-3 break-all">{t('Profile version','Phiên bản hồ sơ')}: {item.version}</p>{profile?.contracts?.length?profile.contracts.map(c=><div className="space-y-1 border-t border-[#34373b] py-3" key={c.event_id}><Badge value={c.state}/><p>{c.reviewer} · {formatEpisodeTime(c.effective_at_ms||0,true,filters.timezone)}</p><p className="break-words">{c.reason}</p>{!!c.expires_at_ms&&<p>{t('Expires','Hết hạn')}: {formatEpisodeTime(c.expires_at_ms,true,filters.timezone)}</p>}</div>):<p>{t('No decisions recorded','Chưa ghi nhận quyết định')}</p>}</details>
  </Page>;
}
