export type Filters = {
  start: string;
  end: string;
  timezone: string;
  environment?: string;
  group?: string;
  module?: string;
  service?: string;
  operation?: string;
  account?: string;
  comparison: string;
};
export type Summary = {
  observed_rps: number;
  observed_tps: number;
  total_requests: number;
  active_services: number;
  active_accounts: number;
  p95_latency_ms: number;
  http_5xx_rate: number;
  slow_request_rate: number;
  active_anomalies: number;
  latest_ingested_ms: number | null;
  sampling_coverage: string;
  tps_equals_rps: boolean;
  sample_count: number;
};
export type SeriesPoint = {
  timestamp_ms: number;
  rps: number;
  tps: number;
  baseline_rps: number;
  p50_ms: number;
  p95_ms: number;
  p99_ms: number;
  http_4xx_rate: number;
  http_5xx_rate: number;
  success_rate: number;
  failure_rate: number;
  sample_count: number;
};
export type Edge = {
  source: string;
  target: string;
  evidence: "confirmed" | "inferred";
  evidence_detail: string;
  requests: number;
  failure_rate: number;
  avg_ms: number;
  freshness_ms: number;
  caller_service?: string;
  target_service?: string;
  rps?: number;
  p95_latency?: number;
  top_principals?: Array<{ principal_name: string; requests: number }>;
  top_operations?: Array<{ operation: string; requests: number }>;
};
export type NodeItem = {
  name: string;
  service_group: string;
  service_module: string;
  environment: string;
  last_seen_ms: number;
};
export type Anomaly = {
  id: number;
  entity_type: string;
  entity_id: string;
  anomaly_type: string;
  first_detected_ms: number;
  last_detected_ms: number;
  window_start_ms?: number;
  window_end_ms?: number;
  current_value: number;
  baseline_value: number | null;
  normal_low: number | null;
  normal_high: number | null;
  absolute_difference: number;
  percent_change: number | null;
  current_samples: number;
  baseline_samples: number;
  persistence_buckets: number;
  delta_percentage?: number | null;
  target_service?: string;
  caller_service?: string;
  principal_name?: string;
  source_ip?: string;
  operation?: string;
  detected_at?: string | number;
  severity: string;
  status: string;
  unit: string;
  explanation: string;
  rule?: string;
  limitations?: string[];
  trace_ids?: string[];
  root_cause?: {
    origin_service: string;
    confidence_score: number;
    reason: string;
    evidence: string[];
  };
  blast_radius?: {
    root_service: string;
    direct_callers: Array<string | { name: string; [key: string]: any }>;
    indirect_callers: Array<string | { name: string; [key: string]: any }>;
    affected_principals: Array<string | { name: string; [key: string]: any }>;
    affected_operations: Array<string | { name: string; [key: string]: any }>;
  };
};
