{{- if .Values.agentStats.enabled }}
{{- $svc := default dict .Values.agentStats.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracescope.fullname" . }}-agent-stats
  labels:
    {{- include "tracescope.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-stats
spec:
  type: {{ default "ClusterIP" $svc.type }}
  selector:
    {{- include "tracescope.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent-stats
  ports:
    - name: http
      port: {{ default 30104 $svc.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq (default "ClusterIP" $svc.type) "NodePort") $svc.nodePort }}
      nodePort: {{ $svc.nodePort }}
      {{- end }}
{{- end }}
