apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracescope.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracescope.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "30102"
    prometheus.io/path: "/metrics"
spec:
  type: {{ (default dict .Values.app.service).type | default "ClusterIP" }}
  selector:
    {{- include "tracescope.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ (default dict .Values.app.service).port | default 30102 }}
      targetPort: http
      protocol: TCP
      {{- if and (eq ((default dict .Values.app.service).type | default "ClusterIP") "NodePort") (default dict .Values.app.service).nodePort }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
