apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracescope.fullname" . }}-api
  labels:
    {{- include "tracescope.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "30102"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    {{- include "tracescope.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 30102
      targetPort: http
      protocol: TCP
