{{- if .Values.clickhouse.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tracescope.fullname" . }}-clickhouse
  labels:
    {{- include "tracescope.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  serviceName: {{ include "tracescope.fullname" . }}-clickhouse
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "tracescope.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: clickhouse
  template:
    metadata:
      labels:
        {{- include "tracescope.labels" . | nindent 8 }}
        app.kubernetes.io/component: clickhouse
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: clickhouse
          image: "{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}"
          imagePullPolicy: {{ .Values.clickhouse.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8123
            - name: native
              containerPort: 9000
          env:
            - name: CLICKHOUSE_DB
              value: {{ .Values.clickhouse.database | quote }}
            - name: CLICKHOUSE_USER
              value: {{ .Values.clickhouse.user | quote }}
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "tracescope.secretName" . }}
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
          startupProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.clickhouse.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "tracescope.fullname" . }}-clickhouse-data
{{- end }}
