{{- if .Values.ingest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracescope.fullname" . }}-ingest
  labels:
    {{- include "tracescope.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
spec:
  type: {{ .Values.ingest.service.type | default "ClusterIP" }}
  selector:
    {{- include "tracescope.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
  ports:
    - name: http
      port: {{ .Values.ingest.service.port | default 30103 }}
      targetPort: http
      protocol: TCP
      {{- if and (eq (.Values.ingest.service.type | default "ClusterIP") "NodePort") .Values.ingest.service.nodePort }}
      nodePort: {{ .Values.ingest.service.nodePort }}
      {{- end }}
{{- end }}
