apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracescope.fullname" . }}-ingest
  labels:
    {{- include "tracescope.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
spec:
  type: ClusterIP
  selector:
    {{- include "tracescope.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
  ports:
    - name: http
      port: 30103
      targetPort: http
      protocol: TCP
