{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracescope.fullname" . }}-secrets
  labels:
    {{- include "tracescope.labels" . | nindent 4 }}
type: Opaque
stringData:
  OTEL_INTERNAL_API_TOKEN: {{ .Values.secrets.internalApiToken | quote }}
  OTEL_API_KEY: {{ .Values.secrets.apiKey | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | quote }}
{{- end }}
