apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracescope.fullname" . }}-app
  labels:
    {{- include "tracescope.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    {{- include "tracescope.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: internal-http
      port: 8000
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracescope.fullname" . }}-storage
  labels:
    {{- include "tracescope.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    {{- include "tracescope.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: internal-http
      port: 8000
      targetPort: http
      protocol: TCP
